// Code generated by hertz generator.

package http

import (
	handler "DaisyClubHouse/biz/handler"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/healthy", handler.Healthy)

	// your code ...
}
