// Code generated by hertz generator.

package room

import (
	"context"

	room "DaisyClubHouse/biz/model/room"
	"github.com/cloudwego/hertz/pkg/app"
)

// CreateRoom .
// @router /api/room/create [POST]
func CreateRoom(ctx context.Context, c *app.RequestContext) {
	var err error
	var req room.CreateRoomReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(400, err.Error())
		return
	}

	resp := new(room.CreateRoomResp)

	c.JSON(200, resp)
}
