// Code generated by hertz generator.

package Room

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _roomMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createroomMw() []app.HandlerFunc {
	// your code...
	return nil
}
